#!/usr/bin/env python3
"""Generates the seven synthetic demo PDFs used to exercise document upload.

These are plain-text *summary* sheets about a fictional person (Maya Patel),
not reproductions of any real government form — no official layouts,
seals, barcodes, or signatures. Every page carries a prominent synthetic
disclaimer. All dates/facts match sample_documents/demo_profile.json.

Usage:
    python scripts/generate_synthetic_pdfs.py

Requires reportlab (see scripts/requirements.txt); not a runtime dependency
of the FastAPI backend.
"""

from __future__ import annotations

import textwrap
from pathlib import Path

from reportlab.lib.colors import HexColor
from reportlab.lib.pagesizes import LETTER
from reportlab.pdfgen import canvas

REPO_ROOT = Path(__file__).resolve().parent.parent
OUTPUT_DIR = REPO_ROOT / "sample_documents" / "pdfs"

DISCLAIMER = "SYNTHETIC DEMO DOCUMENT — NOT AN OFFICIAL RECORD."
BANNER_BG = HexColor("#fee2e2")
BANNER_TEXT = HexColor("#991b1b")
BODY_TEXT = HexColor("#111111")
LABEL_TEXT = HexColor("#374151")
PAGE_WIDTH, PAGE_HEIGHT = LETTER
MARGIN = 0.75 * 72


def _draw_banner(c: canvas.Canvas, y: float) -> None:
    c.setFillColor(BANNER_BG)
    c.rect(MARGIN, y, PAGE_WIDTH - 2 * MARGIN, 26, fill=1, stroke=0)
    c.setFillColor(BANNER_TEXT)
    c.setFont("Helvetica-Bold", 11)
    c.drawCentredString(PAGE_WIDTH / 2, y + 8, DISCLAIMER)


def render_pdf(
    path: Path,
    *,
    title: str,
    subtitle: str,
    fields: list[tuple[str, str]] | None = None,
    paragraphs: list[str] | None = None,
) -> None:
    c = canvas.Canvas(str(path), pagesize=LETTER)

    top_banner_y = PAGE_HEIGHT - MARGIN - 26
    _draw_banner(c, top_banner_y)

    cursor_y = top_banner_y - 40

    c.setFillColor(BODY_TEXT)
    c.setFont("Helvetica-Bold", 16)
    c.drawString(MARGIN, cursor_y, title)
    cursor_y -= 20

    c.setFont("Helvetica-Oblique", 10)
    c.setFillColor(LABEL_TEXT)
    c.drawString(MARGIN, cursor_y, subtitle)
    cursor_y -= 28

    c.setFont("Helvetica", 9)
    c.setFillColor(LABEL_TEXT)
    c.drawString(
        MARGIN,
        cursor_y,
        "Generated by Proofly for the Open Atlas 2026 demo. All names, IDs, and dates below are fictional.",
    )
    cursor_y -= 26

    if fields:
        for label, value in fields:
            c.setFont("Helvetica-Bold", 10)
            c.setFillColor(LABEL_TEXT)
            c.drawString(MARGIN, cursor_y, f"{label}:")
            c.setFont("Helvetica", 10)
            c.setFillColor(BODY_TEXT)
            c.drawString(MARGIN + 190, cursor_y, value)
            cursor_y -= 18
        cursor_y -= 10

    if paragraphs:
        c.setFont("Helvetica", 10)
        c.setFillColor(BODY_TEXT)
        for paragraph in paragraphs:
            for line in textwrap.wrap(paragraph, width=92):
                c.drawString(MARGIN, cursor_y, line)
                cursor_y -= 14
            cursor_y -= 10

    bottom_banner_y = MARGIN
    _draw_banner(c, bottom_banner_y)
    c.setFont("Helvetica", 8)
    c.setFillColor(LABEL_TEXT)
    c.drawCentredString(
        PAGE_WIDTH / 2,
        bottom_banner_y - 14,
        "Fictional identifiers only — not associated with any real person, institution, or agency.",
    )

    c.showPage()
    c.save()


def main() -> None:
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

    render_pdf(
        OUTPUT_DIR / "Maya_Patel_I20_Summary.pdf",
        title="I-20 Summary — Certificate of Eligibility (Fictional)",
        subtitle="Plain-text summary of I-20 details. Not a reproduction of the official SEVP form.",
        fields=[
            ("Student Name", "Maya Patel (fictional)"),
            ("SEVIS ID", "N0012345678 (fictional)"),
            ("School", "Northbridge University (fictional institution)"),
            ("Program of Study", "M.S. Computer Science"),
            ("Program Start Date", "August 22, 2022"),
            ("Program End Date", "May 18, 2024"),
            ("Visa Classification Sought", "F-1"),
        ],
    )

    render_pdf(
        OUTPUT_DIR / "Maya_Patel_I94_Summary.pdf",
        title="I-94 Summary — Arrival/Departure Record (Fictional)",
        subtitle="Plain-text summary of I-94 details. Not a reproduction of the official CBP record.",
        fields=[
            ("Traveler Name", "Maya Patel (fictional)"),
            ("Most Recent Date of Entry", "August 19, 2022"),
            ("Class of Admission", "F-1"),
            ("Admit Until Date", "D/S (Duration of Status)"),
        ],
        paragraphs=[
            "Note: 'D/S' means this admission has no fixed expiration date printed on the record. "
            "This summary intentionally does not invent one.",
        ],
    )

    render_pdf(
        OUTPUT_DIR / "Maya_Patel_EAD_Summary.pdf",
        title="Employment Authorization Summary (Fictional)",
        subtitle="Plain-text summary of EAD card details. Not a reproduction of the official USCIS card.",
        fields=[
            ("Cardholder", "Maya Patel (fictional)"),
            ("Category (Card 1)", "C3B — Post-Completion OPT"),
            ("Card 1 Valid", "July 1, 2024 – June 30, 2025"),
            ("Category (Card 2)", "C3C — 24-Month STEM OPT Extension"),
            ("Card 2 Valid", "July 1, 2025 – June 30, 2027"),
        ],
        paragraphs=[
            "These dates describe employment authorization only — they are separate from, and do not "
            "represent, F-1 status or visa stamp expiration.",
        ],
    )

    render_pdf(
        OUTPUT_DIR / "Maya_Patel_Resume.pdf",
        title="Maya Patel — Resume (Fictional)",
        subtitle="Synthetic demo resume.",
        fields=[
            ("Current Title", "Machine Learning Engineer"),
            ("Current Employer", "Lumina AI Labs, Inc. (fictional company)"),
            ("Employment Period", "July 2024 – Present"),
            ("Education", "M.S. Computer Science, Northbridge University (fictional), 2024"),
        ],
        paragraphs=[
            "Summary: Fictional demo profile created for the Proofly Open Atlas 2026 hackathon build. "
            "Not a real person's employment or education history.",
        ],
    )

    render_pdf(
        OUTPUT_DIR / "Maya_Patel_Employment_Letter.pdf",
        title="Employment Verification Letter (Fictional)",
        subtitle="Synthetic demo employment letter — not an authentic company document.",
        paragraphs=[
            "This letter confirms that Maya Patel (fictional) is employed at Lumina AI Labs, Inc. "
            "(fictional company) in the role of Machine Learning Engineer, with an effective start "
            "date of July 15, 2024.",
            "Maya leads the core model-fairness research initiative and reports directly to the "
            "Head of AI Research.",
            "— Fictional HR Contact, Lumina AI Labs, Inc. (no signature; synthetic demo document)",
        ],
    )

    render_pdf(
        OUTPUT_DIR / "Maya_Patel_Innovation_Award.pdf",
        title="Best Emerging Researcher Award (Fictional)",
        subtitle="Synthetic demo award notice — not an authentic certificate.",
        fields=[
            ("Recipient", "Maya Patel (fictional)"),
            ("Award", "Best Emerging Researcher Award"),
            (
                "Issuing Organization",
                "International Conference on Machine Learning Applications (ICMLA) (fictional for demo)",
            ),
            ("Award Date", "November 8, 2024"),
        ],
    )

    render_pdf(
        OUTPUT_DIR / "Maya_Patel_Judging_Invitation.pdf",
        title="Judging Invitation (Fictional)",
        subtitle="Synthetic demo invitation letter — not an authentic event communication.",
        paragraphs=[
            "You are invited to serve as a judge for the TechBridge Summit 2026 Student Poster "
            "Competition (fictional event), scheduled for September 5, 2026.",
            "This is a fictional invitation generated for Proofly demo purposes only.",
        ],
    )

    generated = sorted(OUTPUT_DIR.glob("*.pdf"))
    print(f"Generated {len(generated)} synthetic PDFs in {OUTPUT_DIR}:")
    for path in generated:
        print(f"  {path.name} ({path.stat().st_size} bytes)")


if __name__ == "__main__":
    main()
